### ISSUE TITLE
Sample usage within a list?

### ISSUE THREAD

**Issue by amanzan** [klinker24/Android-SimpleVideoView#4] opened 2018-03-06 08:53 UTC
Link to your GiffySearch file does not work, I tried to search in your Talon-for-Twitter project with no success. Would you mind sharing a brief example of the proper way to work on a RecyclerView?

**Comment by klinker24** [comment] 2018-03-06 14:27
This is a duplicate of #2, I haven't put together a sample around this yet, sorry.

**Closed as completed by klinker24** 2018-03-06 14:27 UTC
